
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.imageio.stream.FileImageInputStream;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTML;
import oracle.jdbc.OraclePreparedStatement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Drimik
 */
public class ADD_Student extends javax.swing.JFrame {
      Connection con2 = null;
    PreparedStatement pst2 = null;
    ResultSet rs2 =  null;
   

    /**
     * Creates new form ADD_Student
     */
    public ADD_Student() {
        initComponents();
        
    }
    public ImageIcon ResizeImage(String ImagePath)
    {
      ImageIcon MyImage= new ImageIcon(ImagePath);
      Image img = MyImage.getImage();
      Image newImg= img.getScaledInstance(image.getWidth(),image.getHeight(),Image.SCALE_SMOOTH);
      ImageIcon image= new ImageIcon(newImg);
      return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        first_nam_text = new javax.swing.JTextField();
        fathers_name_text = new javax.swing.JTextField();
        mothers_name_text = new javax.swing.JTextField();
        last_name_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        dpt_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Intake_text = new javax.swing.JTextField();
        Section_text = new javax.swing.JTextField();
        Age_Text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DOB_text = new javax.swing.JTextField();
        religion_txt = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        address_txt1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jB_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("S_ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 140, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("First_Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 180, 26);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Last_Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 140, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Father's Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 85, 38);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Mother's Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 91, 38);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 210, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("Religion");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 20, 80, 38);

        id_text.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });
        getContentPane().add(id_text);
        id_text.setBounds(160, 30, 180, 30);

        first_nam_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        first_nam_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nam_textActionPerformed(evt);
            }
        });
        getContentPane().add(first_nam_text);
        first_nam_text.setBounds(160, 80, 180, 30);

        fathers_name_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fathers_name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathers_name_textActionPerformed(evt);
            }
        });
        getContentPane().add(fathers_name_text);
        fathers_name_text.setBounds(160, 170, 180, 30);

        mothers_name_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mothers_name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothers_name_textActionPerformed(evt);
            }
        });
        getContentPane().add(mothers_name_text);
        mothers_name_text.setBounds(160, 230, 180, 30);

        last_name_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        last_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_name_txtActionPerformed(evt);
            }
        });
        getContentPane().add(last_name_txt);
        last_name_txt.setBounds(160, 120, 180, 30);

        address_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });
        getContentPane().add(address_txt);
        address_txt.setBounds(520, 180, 170, 102);

        dpt_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dpt_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpt_textActionPerformed(evt);
            }
        });
        getContentPane().add(dpt_text);
        dpt_text.setBounds(230, 380, 170, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Department");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 380, 80, 40);

        Intake_text.setText("Numeric Form");
        Intake_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Intake_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Intake_textMouseClicked(evt);
            }
        });
        Intake_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Intake_textActionPerformed(evt);
            }
        });
        getContentPane().add(Intake_text);
        Intake_text.setBounds(230, 440, 170, 40);

        Section_text.setText("Numeric Form");
        Section_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Section_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Section_textMouseClicked(evt);
            }
        });
        Section_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Section_textActionPerformed(evt);
            }
        });
        getContentPane().add(Section_text);
        Section_text.setBounds(230, 490, 170, 40);

        Age_Text.setText("Numeric Form");
        Age_Text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Age_Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Age_TextMouseClicked(evt);
            }
        });
        Age_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_TextActionPerformed(evt);
            }
        });
        getContentPane().add(Age_Text);
        Age_Text.setBounds(520, 70, 110, 31);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("Intake");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 430, 90, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("Section");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 490, 80, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setText("Age");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(370, 60, 67, 59);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setText("gender");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(370, 120, 80, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setText("DOB");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(370, 150, 100, 30);

        DOB_text.setText("DD-MM-YY");
        DOB_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DOB_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOB_textMouseClicked(evt);
            }
        });
        DOB_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOB_textActionPerformed(evt);
            }
        });
        getContentPane().add(DOB_text);
        DOB_text.setBounds(520, 140, 180, 30);

        religion_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        religion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religion_txtActionPerformed(evt);
            }
        });
        getContentPane().add(religion_txt);
        religion_txt.setBounds(520, 30, 180, 30);

        jRadioButton1.setText("Male");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseReleased(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(520, 120, 47, 23);

        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(580, 120, 110, 23);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 255));
        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 520, 210, 30);

        image.setBackground(new java.awt.Color(0, 0, 0));
        image.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        image.setForeground(new java.awt.Color(255, 153, 153));
        image.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 255, 0), new java.awt.Color(0, 102, 51)));
        image.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(image);
        image.setBounds(490, 310, 240, 150);

        jButton2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 255));
        jButton2.setText("Save");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 590, 90, 50);

        address_txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        address_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(address_txt1);
        address_txt1.setBounds(520, 480, 210, 30);

        jButton3.setText("Display");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 590, 110, 50);

        jButton4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("BACK");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 590, 90, 50);

        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 102), 4), "Student_ Personal_Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 10, 730, 300);

        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "Academic_Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 310, 730, 250);

        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 4), "Button", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 570, 700, 100);

        jB_logout.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jB_logout.setForeground(new java.awt.Color(204, 0, 204));
        jB_logout.setText("Logout");
        jB_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(jB_logout);
        jB_logout.setBounds(340, 590, 100, 50);

        setSize(new java.awt.Dimension(763, 732));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textActionPerformed

    private void first_nam_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nam_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_nam_textActionPerformed

    private void fathers_name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathers_name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathers_name_textActionPerformed

    private void mothers_name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothers_name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothers_name_textActionPerformed

    private void last_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_name_txtActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void dpt_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpt_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpt_textActionPerformed

    private void Intake_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Intake_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Intake_textActionPerformed

    private void Section_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Section_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Section_textActionPerformed

    private void Age_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_TextActionPerformed

    private void DOB_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOB_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB_textActionPerformed

    private void religion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religion_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religion_txtActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1MouseReleased

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        ;  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void address_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        File f=  chooser.getSelectedFile();
          int Result = 0;
        if(Result==JFileChooser.APPROVE_OPTION)
        {
           
        Filename= f.getAbsolutePath();
        address_txt1.setText(Filename);
        image.setIcon(ResizeImage(Filename));
        }
      
       
        
        try{
            
 File image=new File (Filename);
FileInputStream fis=new FileInputStream(image);
ByteArrayOutputStream bos=new ByteArrayOutputStream();
byte[] buf= new byte[1024];
for(int readNum ;(readNum = fis.read(buf))!=-1;)
   
{
	bos.write(buf,0,readNum);
}
person_image= bos.toByteArray();


}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null, e);
}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              // TODO add your handling code here:
              
         try{
            String sql = "INSERT INTO personal_details"
                    +"(ID,first_name,last_name,fathers_name,mothers_name,address,religion,department,intake,section,age,gender,dob,pic)"
                    +"VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
             con2 =  JavaConnectDb.connectrDb();
              pst2 = con2.prepareStatement(sql);
              pst2.setString(1,id_text.getText());
              pst2.setString(2,first_nam_text.getText());
              pst2.setString(3,last_name_txt.getText());
              pst2.setString(4,fathers_name_text.getText());
              pst2.setString(5, mothers_name_text.getText());
              pst2.setString(6, address_txt.getText());
              pst2.setString(7, religion_txt.getText());
              pst2.setString(8,dpt_text.getText());
              pst2.setString(9,Intake_text.getText());
              
                pst2.setString(10,Section_text.getText());
                pst2.setString(11,Age_Text.getText());
               if(jRadioButton1.isSelected())
                  {pst2.setString(12,"Male");}  
                                 
                 if(jRadioButton2.isSelected())
                                         { pst2.setString(12,"Female");
                                         }
                                        
               pst2.setString(13,DOB_text.getText());
               
                    pst2.setBytes(14, person_image);
                                                  
              
              
              
              
                            
              
                 

              
              pst2.executeUpdate();
     
       
              
              JOptionPane.showMessageDialog(null, "inserted successfully");
                     JOptionPane OptionPane=JOptionPane();
                     id_text.setText("");
                     
            
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null,"check the constraint ID must be DIGIT  ");
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            image.setIcon(null);        // TODO add your handling code here:
                 try {
            String sql = "select PIC from personal_details where ID=?";
              con2 =  JavaConnectDb.connectrDb();
              pst2 = con2.prepareStatement(sql);
              pst2.setString(1,id_text.getText());
              rs2=pst2.executeQuery();
              
                
              if(rs2.next())
              {
                
             byte [] imagedata = rs2.getBytes("pic") ;
             BufferedImage buff_image=ImageIO.read(new ByteArrayInputStream(imagedata));
               format = new ImageIcon(buff_image);
             image.setIcon(format);
             
             
              }
        } catch (Exception e) {
            e.printStackTrace();
        }
                
                   try{
                     }
                 catch(Exception e)
                 {
                 }
                   finally{
                       try {
                           rs2.close();
                           pst2.close();
                       } catch (Exception e) {
                       }
                   }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Intake_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Intake_textMouseClicked
Intake_text.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Intake_textMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      student_main_form sdd=new student_main_form();
      sdd.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Age_TextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Age_TextMouseClicked
Age_Text.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Age_TextMouseClicked

    private void Section_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Section_textMouseClicked
Section_text.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Section_textMouseClicked

    private void jB_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logoutActionPerformed
        // TODO add your handling code here:
        login_2  c= new login_2();
        c.setVisible(true);
        this.dispose();
        try {
            con2=JavaConnectDb.connectrDb();
            Date curreDate=GregorianCalendar.getInstance().getTime();
            DateFormat df= DateFormat.getDateInstance();
            String dateString=df.format(curreDate);
            Date d= new Date();
            SimpleDateFormat sdf= new SimpleDateFormat("HH:MM:SS");
            String timeString=sdf.format(d);
            String valueo=timeString;
            String values =dateString;
            int value=employee.empid;
            String valuetype=employee.Emptype;
            String reg="INSERT INTO AUDIT_TABLE(TYPE,EMP_ID,DATE_USE,STATUS) VALUES ('"+valuetype+ "','"+value+ "','"+valueo+" / "+values+"','logged out' )";
            pst2=(OraclePreparedStatement) con2.prepareStatement(reg);
            pst2.executeQuery();
        } catch (Exception e) {
        }
        finally{try {
            rs2.close();
            pst2.close();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jB_logoutActionPerformed

    private void DOB_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOB_textMouseClicked
      DOB_text.setText("");
    }//GEN-LAST:event_DOB_textMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age_Text;
    private javax.swing.JTextField DOB_text;
    private javax.swing.JTextField Intake_text;
    private javax.swing.JTextField Section_text;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField address_txt1;
    private javax.swing.JTextField dpt_text;
    private javax.swing.JTextField fathers_name_text;
    private javax.swing.JTextField first_nam_text;
    private javax.swing.JTextField id_text;
    private javax.swing.JLabel image;
    private javax.swing.JButton jB_logout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField last_name_txt;
    private javax.swing.JTextField mothers_name_text;
    private javax.swing.JTextField religion_txt;
    // End of variables declaration//GEN-END:variables
String Filename=null;
int s=0;
byte[] person_image=null;
private  ImageIcon format=null;

    private JOptionPane JOptionPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
