
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Drimik
 */
public class ADD_Courses extends javax.swing.JFrame {
    String gotsem;
    String gotyear;
    String gotsid;
   

    /**
     * Creates new form ADD_Courses
     */
      Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    public ADD_Courses() {
        initComponents();
         conn = JavaConnectDb.connectrDb();
         jt_cname_1.setText("");
         fillcombo();
        
    }
    public void  fillcombo()
    {
        try {
         
      String sql= "select * from COURSE_LIST ";
           pst=(OraclePreparedStatement) conn.prepareStatement(sql);
             rs = (OracleResultSet) pst.executeQuery();
             
             while (rs.next()) {
                  String sname=rs.getString("coursecode");
                 jComboBox_c4.addItem(sname);
                 jComboBox_c3.addItem(sname);
                  jComboBox_c_2.addItem(sname);
                  jComboBox_c1.addItem(sname);
            
                 
        }
        }
             catch (Exception e) {
                
                }
        finally{
            try {
                rs.close();
                pst.close();;
            } catch (Exception e) {
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTx_sid = new javax.swing.JTextField();
        jComboBox_c4 = new javax.swing.JComboBox<>();
        jlable_c1 = new javax.swing.JLabel();
        jLabelc_2 = new javax.swing.JLabel();
        jalabe_c_3 = new javax.swing.JLabel();
        jt_cname_1 = new javax.swing.JTextField();
        jt_c_name_3 = new javax.swing.JTextField();
        jt_cname_4 = new javax.swing.JTextField();
        jLabel_c_6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_cname_2 = new javax.swing.JTextField();
        jLabel_sid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_sem = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_type4 = new javax.swing.JComboBox<>();
        jComboBox_type1 = new javax.swing.JComboBox<>();
        jComboBox_type2 = new javax.swing.JComboBox<>();
        jComboBox_type3 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButtonc_1 = new javax.swing.JButton();
        jButtonc_2 = new javax.swing.JButton();
        jButtonc_3 = new javax.swing.JButton();
        jComboBox_year = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_c_7 = new javax.swing.JLabel();
        jComboBox_c1 = new javax.swing.JComboBox<>();
        jComboBox_c_2 = new javax.swing.JComboBox<>();
        jComboBox_c3 = new javax.swing.JComboBox<>();
        jlabel_credit1 = new javax.swing.JTextField();
        jlabel_credit2 = new javax.swing.JTextField();
        jlabel_credit3 = new javax.swing.JTextField();
        jlabel_credit4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jB_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTx_sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTx_sidActionPerformed(evt);
            }
        });
        getContentPane().add(jTx_sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 180, 30));

        jComboBox_c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox_c4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox_c4MouseReleased(evt);
            }
        });
        jComboBox_c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_c4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 110, 30));

        jlable_c1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlable_c1.setText("COURSE CODE");
        getContentPane().add(jlable_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, 30));

        jLabelc_2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc_2.setText("1");
        getContentPane().add(jLabelc_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 50, 30));

        jalabe_c_3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jalabe_c_3.setText("2");
        getContentPane().add(jalabe_c_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 60, 30));

        jt_cname_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_cname_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jt_cname_1MouseEntered(evt);
            }
        });
        jt_cname_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_cname_1ActionPerformed(evt);
            }
        });
        jt_cname_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_cname_1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_cname_1KeyTyped(evt);
            }
        });
        getContentPane().add(jt_cname_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 180, 30));

        jt_c_name_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_c_name_3ActionPerformed(evt);
            }
        });
        jt_c_name_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_c_name_3KeyReleased(evt);
            }
        });
        getContentPane().add(jt_c_name_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 180, 30));

        jt_cname_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_cname_4ActionPerformed(evt);
            }
        });
        jt_cname_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_cname_4KeyReleased(evt);
            }
        });
        getContentPane().add(jt_cname_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 180, 30));

        jLabel_c_6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_c_6.setText("3");
        getContentPane().add(jLabel_c_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 120, 20));

        jt_cname_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_cname_2KeyReleased(evt);
            }
        });
        getContentPane().add(jt_cname_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 180, 30));

        jLabel_sid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_sid.setText("S_ID");
        getContentPane().add(jLabel_sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 30));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("Year");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 90, 30));

        jComboBox_sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall", "Summer", "Spring" }));
        jComboBox_sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_semActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 80, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Credit");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 90, 30));

        jComboBox_type4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Retake" }));
        getContentPane().add(jComboBox_type4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 90, 30));

        jComboBox_type1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Retake" }));
        getContentPane().add(jComboBox_type1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 90, 30));

        jComboBox_type2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Retake" }));
        getContentPane().add(jComboBox_type2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 90, 30));

        jComboBox_type3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Retake" }));
        getContentPane().add(jComboBox_type3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 90, 30));

        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 60, 30));

        jButtonc_1.setText("SAVE");
        jButtonc_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonc_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonc_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 60, 30));

        jButtonc_2.setText("SAVE");
        jButtonc_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonc_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonc_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 60, 30));

        jButtonc_3.setText("SAVE");
        jButtonc_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonc_3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonc_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 60, 30));

        jComboBox_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jComboBox_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_yearActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 70, 30));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 204), 5), "ADD Course ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bodoni MT", 3, 18), new java.awt.Color(255, 51, 51))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 700, 50));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("Semester");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 90, 30));

        jLabel_c_7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_c_7.setText("4");
        getContentPane().add(jLabel_c_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 50, 20));

        jComboBox_c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_c1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_c1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox_c1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox_c1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox_c1MouseReleased(evt);
            }
        });
        jComboBox_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_c1ActionPerformed(evt);
            }
        });
        jComboBox_c1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox_c1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox_c1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox_c1KeyTyped(evt);
            }
        });
        getContentPane().add(jComboBox_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 110, 30));

        jComboBox_c_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox_c_2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox_c_2MouseReleased(evt);
            }
        });
        jComboBox_c_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_c_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_c_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 110, 30));

        jComboBox_c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox_c3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox_c3MouseReleased(evt);
            }
        });
        jComboBox_c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_c3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 110, 30));

        jlabel_credit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_credit1MouseClicked(evt);
            }
        });
        jlabel_credit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlabel_credit1ActionPerformed(evt);
            }
        });
        getContentPane().add(jlabel_credit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 100, 30));

        jlabel_credit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_credit2MouseClicked(evt);
            }
        });
        jlabel_credit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlabel_credit2ActionPerformed(evt);
            }
        });
        getContentPane().add(jlabel_credit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 100, 30));

        jlabel_credit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_credit3MouseClicked(evt);
            }
        });
        jlabel_credit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlabel_credit3ActionPerformed(evt);
            }
        });
        getContentPane().add(jlabel_credit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 100, 30));

        jlabel_credit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_credit4MouseClicked(evt);
            }
        });
        jlabel_credit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlabel_credit4ActionPerformed(evt);
            }
        });
        getContentPane().add(jlabel_credit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 100, 30));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51), 6), "FIll First", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 102, 255))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 720, 90));

        jButton2.setText("BACK To Home");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 130, 40));

        jB_logout.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jB_logout.setForeground(new java.awt.Color(255, 51, 51));
        jB_logout.setText("Logout");
        jB_logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jB_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(jB_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 120, 40));

        setSize(new java.awt.Dimension(720, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_cname_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_cname_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_cname_4ActionPerformed

    private void jComboBox_c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_c4ActionPerformed
jt_cname_4.setText("");
        String c1=(String) jComboBox_c4.getSelectedItem();
       jt_cname_4.setText(c1);
       
        
          
        
               // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox_c4ActionPerformed

    private void jt_cname_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cname_1MouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_jt_cname_1MouseEntered

    private void jt_cname_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cname_1MouseClicked
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_jt_cname_1MouseClicked

    private void jt_cname_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_cname_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_cname_1ActionPerformed

    private void jComboBox_c4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c4MousePressed

                // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c4MousePressed

    private void jComboBox_c4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c4MouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox_c4MouseReleased

    private void jt_cname_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_cname_1KeyReleased
try {
                  String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";
                
               pst=(OraclePreparedStatement) conn.prepareStatement(sql);
               pst.setString(1, jt_cname_1.getText());
 
               rs=(OracleResultSet) pst.executeQuery();
               while(rs.next())
               {
               
               String add1=rs.getString("CREDIT");
             jlabel_credit1.setText(add1);
                  
             
                 
               }                          
                              
                           
                
                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{try {
                pst.close();;
                    rs.close();
                } catch (Exception e) {
                }
}          // TODO add your handling code here:
            
    }//GEN-LAST:event_jt_cname_1KeyReleased

    private void jt_cname_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_cname_2KeyReleased
try {
                  String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";
                
               pst=(OraclePreparedStatement) conn.prepareStatement(sql);
               pst.setString(1,jt_cname_2.getText());
 
               rs=(OracleResultSet) pst.executeQuery();
               while(rs.next())
               {
               
               String add2=rs.getString("CREDIT");
             jlabel_credit2.setText(add2);
                  
             
                 
               }                          
                              
                           
                
                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{try {
                pst.close();;
                    rs.close();
                } catch (Exception e) {
                }
}           
    }//GEN-LAST:event_jt_cname_2KeyReleased

    private void jt_c_name_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_c_name_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_c_name_3ActionPerformed

    private void jt_c_name_3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_c_name_3KeyReleased
try {
                  String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";
                
               pst=(OraclePreparedStatement) conn.prepareStatement(sql);
               pst.setString(1, jt_c_name_3.getText());
 
               rs=(OracleResultSet) pst.executeQuery();
               while(rs.next())
               {
               
               String add1=rs.getString("CREDIT");
           jlabel_credit3.setText(add1);
          
                 
            
                 
               }                          
                              
                           
                
                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{try {
                pst.close();;
                    rs.close();
                } catch (Exception e) {
                }
}         // TODO add your handling code here:
    }//GEN-LAST:event_jt_c_name_3KeyReleased

    private void jt_cname_4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_cname_4KeyReleased
    try {
                  String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";
                
               pst=(OraclePreparedStatement) conn.prepareStatement(sql);
               pst.setString(1, jt_cname_4.getText());
 
               rs=(OracleResultSet) pst.executeQuery();
               while(rs.next())
               {
               
               String add1=rs.getString("CREDIT");
jlabel_credit4.setText(add1);
              float t1=Float.parseFloat(jlabel_credit1.getText());
         
                 float t2=Float.parseFloat(jlabel_credit2.getText());
                  float t3=Float.parseFloat(jlabel_credit3.getText());
                   float t4=Float.parseFloat(jlabel_credit4.getText());
                 
                 
                 
               }                          
                              
                           
                
                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{try {
                pst.close();;
                    rs.close();
                } catch (Exception e) {
                }
}         // TODO add your handling code here:
    }//GEN-LAST:event_jt_cname_4KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try {
              String sql2="select * from SEMESTER_REGISTRATION where SEMESTER_REGISTRATION.SID='"+gotsid+"' and SEMESTER_REGISTRATION.SEMESTER='"+gotsem+"' and SEMESTER_REGISTRATION.YEAR='"+gotyear+"'";    
             pst = (OraclePreparedStatement) conn.prepareStatement(sql2);
            rs = (OracleResultSet) pst.executeQuery();
            
            if(rs.next())
            {  
                     
        try{
           
              
              pst=(OraclePreparedStatement) conn.prepareStatement(sql);
              pst.setString(1,jTx_sid.getText());
              pst.setString(2,jt_cname_4.getText());
              pst.setString(3,jComboBox_sem.getSelectedItem().toString());
              pst.setString(4,jComboBox_type4.getSelectedItem().toString());
 
               pst.setString(5,jComboBox_year.getSelectedItem().toString());
             try {
               pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "inserted successfully");
     } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"AllReady Added This Course ");
     }
              
          
            
              
            
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null,"check the constraint ID must be DIGIT  ");
            
        } 
            }
            else
            {
                JOptionPane.showMessageDialog(null,"'"+gotsid+"' this is is not registerd for the semester '"+gotsem+"' ");
            }
        }
            catch (Exception e) {
           JOptionPane.showMessageDialog(null,e);
     }
      
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonc_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonc_1ActionPerformed
    
        gotyear=jComboBox_year.getSelectedItem().toString();
        gotsem=jComboBox_sem.getSelectedItem().toString();
        gotsid=jTx_sid.getText();
       String  gotcoursecode=jt_cname_1.getText();
        String sql2="select * from SEMESTER_REGISTRATION where SEMESTER_REGISTRATION.SID='"+gotsid+"' and SEMESTER_REGISTRATION.SEMESTER='"+gotsem+"' and SEMESTER_REGISTRATION.YEAR='"+gotyear+"'";

        try {
             pst = (OraclePreparedStatement) conn.prepareStatement(sql2);
            rs = (OracleResultSet) pst.executeQuery();
            if(rs.next())
            {
               
            try{
           
              
              pst=(OraclePreparedStatement) conn.prepareStatement(sql);
              pst.setString(1,jTx_sid.getText());
              pst.setString(2,jt_cname_1.getText());
              pst.setString(3,jComboBox_sem.getSelectedItem().toString());
              pst.setString(4,jComboBox_type2.getSelectedItem().toString());
               pst.setString(5,jComboBox_year.getSelectedItem().toString());
             try {
               pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "inserted successfully");
     } catch (Exception e) {
       
           JOptionPane.showMessageDialog(null,"AllReady Added This Course ");
     }
                
            }
            catch (Exception e) {
                
                }
        }
            else
            {
                JOptionPane.showMessageDialog(null,"'"+gotsid+"' this is is not registerd for the semester '"+gotsem+"' ");
            }
        }
          catch (Exception e) {
              JOptionPane().showMessageDialog(rootPane, e);
                
                }
        
     
     
              
          
            
              
            
        
       
            
        
    }//GEN-LAST:event_jButtonc_1ActionPerformed

    private void jButtonc_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonc_2ActionPerformed
        // TODO add your handling code here:
        try {
             String sql2="select * from SEMESTER_REGISTRATION where  SEMESTER_REGISTRATION.SID='"+gotsid+"' and SEMESTER_REGISTRATION.SEMESTER='"+gotsem+"' and SEMESTER_REGISTRATION.YEAR='"+gotyear+"'";
             pst = (OraclePreparedStatement) conn.prepareStatement(sql2);
            rs = (OracleResultSet) pst.executeQuery();
            if(rs.next())
            {
          try{
           
            
              pst=(OraclePreparedStatement) conn.prepareStatement(sql);
              pst.setString(1,jTx_sid.getText());
              pst.setString(2,jt_cname_2.getText());
              pst.setString(3,jComboBox_sem.getSelectedItem().toString());
              pst.setString(4,jComboBox_type2.getSelectedItem().toString());
               pst.setString(5,jComboBox_year.getSelectedItem().toString());
             try {
               pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "inserted successfully");
     } catch (Exception e) {
             JOptionPane.showMessageDialog(null,"AllReady Added This Course ");
     }
              
          
            
              
            
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null,"Allready Added  ");
            
        }
            }
            else {
                JOptionPane.showMessageDialog(null,"\"'\"+gotsid+\"' this is is not registerd for the semester '\"+gotsem+\"' \"");
            }
            
        }
            catch (Exception e) {
           JOptionPane.showMessageDialog(null,e);
     }
          
    }//GEN-LAST:event_jButtonc_2ActionPerformed

    private void jButtonc_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonc_3ActionPerformed
try {
              String sql2="select * from SEMESTER_REGISTRATION where SEMESTER_REGISTRATION.SID='"+gotsid+"' and SEMESTER_REGISTRATION.SEMESTER='"+gotsem+"' and SEMESTER_REGISTRATION.YEAR='"+gotyear+"'";    
             pst = (OraclePreparedStatement) conn.prepareStatement(sql2);
            rs = (OracleResultSet) pst.executeQuery();
            
            if(rs.next())
            {  
        
        try{
           
              
              pst=(OraclePreparedStatement) conn.prepareStatement(sql);
              pst.setString(1,jTx_sid.getText());
              pst.setString(2,jt_c_name_3.getText());
              pst.setString(3,jComboBox_sem.getSelectedItem().toString());
              pst.setString(4,jComboBox_type3.getSelectedItem().toString());
          
               pst.setString(5,jComboBox_year.getSelectedItem().toString());
             try {
               pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "inserted successfully");
     } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"AllReady Added This Course ");
     }
              
          
            
              
            
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null,"check the constraint ID must be DIGIT  ");
        }
            
        } 
            else {
                JOptionPane.showMessageDialog(null,"\"'\"+gotsid+\"' this is is not registerd for the semester '\"+gotsem+\"' \"");
            }
            
     }
catch (Exception e) {
           JOptionPane.showMessageDialog(null,e);
}   
    }//GEN-LAST:event_jButtonc_3ActionPerformed

    private void jTx_sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTx_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTx_sidActionPerformed

    private void jComboBox_semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_semActionPerformed

    private void jComboBox_c1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c1MousePressed

    private void jComboBox_c1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c1MouseReleased

              // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c1MouseReleased

    private void jComboBox_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_c1ActionPerformed
String c1=(String) jComboBox_c1.getSelectedItem();
       jt_cname_1.setText(c1);        
    
    }//GEN-LAST:event_jComboBox_c1ActionPerformed

    private void jComboBox_c_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c_2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c_2MousePressed

    private void jComboBox_c_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c_2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c_2MouseReleased

    private void jComboBox_c_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_c_2ActionPerformed
        jt_cname_2.setText("");
        String c1=(String) jComboBox_c_2.getSelectedItem();
       jt_cname_2.setText(c1);
    }//GEN-LAST:event_jComboBox_c_2ActionPerformed

    private void jComboBox_c3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c3MousePressed

    private void jComboBox_c3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c3MouseReleased

    private void jComboBox_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_c3ActionPerformed
       jt_c_name_3.setText("");
        String c1=(String) jComboBox_c3.getSelectedItem();
       jt_c_name_3.setText(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c3ActionPerformed

    private void jComboBox_c1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_c1KeyReleased
         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c1KeyReleased

    private void jComboBox_c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c1MouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c1MouseClicked

    private void jComboBox_c1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c1MouseEntered
         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c1MouseEntered

    private void jComboBox_c1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_c1MouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c1MouseExited

    private void jComboBox_c1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_c1KeyPressed
          // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c1KeyPressed

    private void jComboBox_c1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_c1KeyTyped
       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_c1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        student_main_form st1=new student_main_form();
        st1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jB_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logoutActionPerformed
        // TODO add your handling code here:
        login_2  c= new login_2();
        c.setVisible(true);
        this.dispose();
        try {
            Date curreDate=GregorianCalendar.getInstance().getTime();
            DateFormat df= DateFormat.getDateInstance();
            String dateString=df.format(curreDate);
            Date d= new Date();
            SimpleDateFormat sdf= new SimpleDateFormat("HH:MM:SS");
            String timeString=sdf.format(d);
            String valueo=timeString;
            String values =dateString;
            int value=employee.empid;
            String valueType=employee.Emptype;
            String reg="INSERT INTO AUDIT_TABLE(TYPE,EMP_ID,DATE_USE,STATUS) VALUES ('"+value+ "','"+value+ "','"+valueo+" / "+values+"','logged out' )";
            pst=(OraclePreparedStatement) conn.prepareStatement(reg);
            pst.executeQuery();
        } catch (Exception e) {
        }
        finally{try {
            rs.close();
            pst.close();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jB_logoutActionPerformed

    private void jComboBox_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_yearActionPerformed

    private void jt_cname_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_cname_1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_cname_1KeyTyped

    private void jlabel_credit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlabel_credit4ActionPerformed
        try {
            String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";

            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, jt_cname_4.getText());

            rs=(OracleResultSet) pst.executeQuery();
            while(rs.next())
            {

                String add1=rs.getString("CREDIT");
                jlabel_credit4.setText(add1);
                float t1=Float.parseFloat(jlabel_credit1.getText());

                float t2=Float.parseFloat(jlabel_credit2.getText());
                float t3=Float.parseFloat(jlabel_credit3.getText());
                float t4=Float.parseFloat(jlabel_credit4.getText());

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{try {
            pst.close();;
            rs.close();
        } catch (Exception e) {
        }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jlabel_credit4ActionPerformed

    private void jlabel_credit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_credit4MouseClicked
        try {
            String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";

            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, jt_cname_4.getText());

            rs=(OracleResultSet) pst.executeQuery();
            while(rs.next())
            {

                String add1=rs.getString("CREDIT");
                jlabel_credit4.setText(add1);

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{try {
            pst.close();;
            rs.close();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jlabel_credit4MouseClicked

    private void jlabel_credit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlabel_credit3ActionPerformed
        try {
            String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";

            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, jt_c_name_3.getText());

            rs=(OracleResultSet) pst.executeQuery();
            while(rs.next())
            {

                String add1=rs.getString("CREDIT");
                jlabel_credit3.setText(add1);
                float t1=Float.parseFloat(jlabel_credit1.getText());

                float t2=Float.parseFloat(jlabel_credit2.getText());
                float t3=Float.parseFloat(jlabel_credit3.getText());

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{try {
            pst.close();;
            rs.close();
        } catch (Exception e) {
        }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jlabel_credit3ActionPerformed

    private void jlabel_credit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_credit3MouseClicked
        try {
            String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";

            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, jt_c_name_3.getText());

            rs=(OracleResultSet) pst.executeQuery();
            while(rs.next())
            {

                String add1=rs.getString("CREDIT");
                jlabel_credit3.setText(add1);

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{try {
            pst.close();;
            rs.close();
        } catch (Exception e) {
        }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jlabel_credit3MouseClicked

    private void jlabel_credit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlabel_credit2ActionPerformed
        try {
            String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";

            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, jt_cname_2.getText());

            rs=(OracleResultSet) pst.executeQuery();
            while(rs.next())
            {

                String add1=rs.getString("CREDIT");
                jlabel_credit2.setText(add1);
                float t1=Float.parseFloat(jlabel_credit1.getText());

                float t2=Float.parseFloat(jlabel_credit2.getText());
                float tf2=t1+t2;
                String ts2=String.valueOf(tf2);

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{try {
            pst.close();;
            rs.close();
        } catch (Exception e) {
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jlabel_credit2ActionPerformed

    private void jlabel_credit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_credit2MouseClicked
        // TODO add your handling code here:
        try {
            String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";

            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, jt_cname_2.getText());

            rs=(OracleResultSet) pst.executeQuery();
            while(rs.next())
            {

                String add1=rs.getString("CREDIT");
                jlabel_credit2.setText(add1);

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{try {
            pst.close();;
            rs.close();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jlabel_credit2MouseClicked

    private void jlabel_credit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlabel_credit1ActionPerformed
        try {
            String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";

            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, jt_cname_1.getText());

            rs=(OracleResultSet) pst.executeQuery();
            while(rs.next())
            {

                String add1=rs.getString("CREDIT");
                jlabel_credit1.setText(add1);

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{try {
            pst.close();;
            rs.close();
        } catch (Exception e) {
        }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jlabel_credit1ActionPerformed

    private void jlabel_credit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_credit1MouseClicked
        try {
            String sql = "select CREDIT from COURSE_LIST where COURSECODE=?";

            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, jt_cname_1.getText());

            rs=(OracleResultSet) pst.executeQuery();
            while(rs.next())
            {

                String add1=rs.getString("CREDIT");
                jlabel_credit1.setText(add1);

            }

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Course_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{try {
            pst.close();;
            rs.close();
        } catch (Exception e) {
        }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jlabel_credit1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_Courses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_logout;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonc_1;
    private javax.swing.JButton jButtonc_2;
    private javax.swing.JButton jButtonc_3;
    public static javax.swing.JComboBox<String> jComboBox_c1;
    public static javax.swing.JComboBox<String> jComboBox_c3;
    public static javax.swing.JComboBox<String> jComboBox_c4;
    public static javax.swing.JComboBox<String> jComboBox_c_2;
    private javax.swing.JComboBox<String> jComboBox_sem;
    private javax.swing.JComboBox<String> jComboBox_type1;
    private javax.swing.JComboBox<String> jComboBox_type2;
    private javax.swing.JComboBox<String> jComboBox_type3;
    private javax.swing.JComboBox<String> jComboBox_type4;
    private javax.swing.JComboBox<String> jComboBox_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_c_6;
    private javax.swing.JLabel jLabel_c_7;
    private javax.swing.JLabel jLabel_sid;
    private javax.swing.JLabel jLabelc_2;
    private javax.swing.JTextField jTx_sid;
    private javax.swing.JLabel jalabe_c_3;
    private javax.swing.JTextField jlabel_credit1;
    private javax.swing.JTextField jlabel_credit2;
    private javax.swing.JTextField jlabel_credit3;
    private javax.swing.JTextField jlabel_credit4;
    private javax.swing.JLabel jlable_c1;
    private javax.swing.JTextField jt_c_name_3;
    private javax.swing.JTextField jt_cname_1;
    private javax.swing.JTextField jt_cname_2;
    private javax.swing.JTextField jt_cname_4;
    // End of variables declaration//GEN-END:variables

    private JOptionPane JOptionPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     String sql = "INSERT INTO COURSE(STUDENT_ID,COURSE_CODE,SEMESTER,TYPE,YEAR) VALUES (?,?,?,?,?)" ;
    // String sal="INSERT INTO COURSE(STUDENT_ID,COURSE_CODE,SEMESTER,TYPE,CREDIT,YEAR) VALUES (?,?,?,?,?,?) WHERE COURSE_LIST.COURSE_CODE=?";
            
}
