

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Drimik
 */
public class Assigned_Course_View extends javax.swing.JFrame {
      String tota;
      int total;
  Double calculate_Credit;
  int totalRegular;
  String  totaRegular;
   int totalRetake;
   double d = (double) totalRetake;
  String  totaRetake;
 int gotid=employee.empid;
            
            String got1=String.valueOf(gotid);
          
   Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    
    public Assigned_Course_View() {
        initComponents();
        conn=JavaConnectDb.connectrDb();
        jLabel_st.setText(got1);
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void creditmethod()
    {
       
    String Semester=jComboBox_sem.getSelectedItem().toString();
    String year=jComboBox_year.getSelectedItem().toString();
      String sqltotal="SELECT SUM (COURSE_LIST.CREDIT) FROM COURSE_LIST,COURSE WHERE COURSE.STUDENT_ID='"+got1+"' and COURSE.SEMESTER='"+Semester+"' and COURSE.YEAR='"+year+"' and COURSE_LIST.COURSECODE=COURSE.COURSE_CODE";
         try {
            pst=(OraclePreparedStatement) conn.prepareStatement(sqltotal);
            
            rs=(OracleResultSet) pst.executeQuery();
             while(rs.next())
             {
                  total=rs.getInt(1);
                tota=String.valueOf(total);
          jLabel_total_credit.setText(tota);
            calculate_Credit=Double.valueOf(tota);
            
             }
         } catch (SQLException ex) {
             Logger.getLogger(FEESS.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        String sql2="SELECT SUM (COURSE_LIST.CREDIT) FROM COURSE_LIST,COURSE WHERE COURSE.STUDENT_ID='"+got1+"' and COURSE.SEMESTER='"+Semester+"' and COURSE.YEAR='"+year+"'  and COURSE.TYPE='Regular' and COURSE_LIST.COURSECODE=COURSE.COURSE_CODE";
        
         try {
            pst=(OraclePreparedStatement) conn.prepareStatement(sql2);
            
            rs=(OracleResultSet) pst.executeQuery();
             while(rs.next())
             {
                  totalRegular=rs.getInt(1);
                totaRegular=String.valueOf(totalRegular);
            jLabel_regular_credit.setText(totaRegular);
             }
         } catch (SQLException ex) {
             Logger.getLogger(FEESS.class.getName()).log(Level.SEVERE, null, ex);
         }
          String sql3="SELECT SUM (COURSE_LIST.CREDIT) FROM COURSE_LIST,COURSE WHERE COURSE.STUDENT_ID='"+got1+"' and COURSE.SEMESTER='"+Semester+"' and COURSE.YEAR='"+year+"'  and COURSE.TYPE= 'Retake' and COURSE_LIST.COURSECODE=COURSE.COURSE_CODE";
        
         try {
            pst=(OraclePreparedStatement) conn.prepareStatement(sql3);
            
            rs=(OracleResultSet) pst.executeQuery();
             while(rs.next())
             {
                  totalRetake=rs.getInt(1);
                 
               totaRetake=String.valueOf(totalRetake);
               
            jLabel_retake_credit.setText(totaRetake);
             }
         } catch (SQLException ex) {
             Logger.getLogger(FEESS.class.getName()).log(Level.SEVERE, null, ex);
         } 
         // TODO add your handling code here:
                        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_assigned_course = new javax.swing.JTable();
        jComboBox_year = new javax.swing.JComboBox<>();
        jComboBox_sem = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_sid = new javax.swing.JLabel();
        jLabel_st = new javax.swing.JLabel();
        jButton_Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel_Semester = new javax.swing.JLabel();
        jLabel_year = new javax.swing.JLabel();
        jLabel_regular_credit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_total_credit = new javax.swing.JLabel();
        jLabel_retake_credit = new javax.swing.JLabel();
        Retake_Credit = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable_assigned_course.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_assigned_course);

        jComboBox_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jComboBox_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_yearActionPerformed(evt);
            }
        });

        jComboBox_sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall", "Summer", "Spring" }));
        jComboBox_sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_semActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("Year");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("Semester");

        jLabel_sid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_sid.setText("S_ID");

        jLabel_st.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton_Back.setText("Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_Semester.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 102), 2));

        jLabel_year.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 102), 2));

        jLabel_regular_credit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_regular_credit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setText("Total_Credit");

        jLabel_total_credit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_total_credit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_retake_credit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_retake_credit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Retake_Credit.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Retake_Credit.setText("Total_Credit");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Regular_Credit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel_sid, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_st, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jComboBox_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel_Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_year, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Retake_Credit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_regular_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_retake_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_total_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_sem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_sid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_st, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Semester, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel_year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel_total_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_regular_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_retake_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Retake_Credit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_yearActionPerformed
        
    }//GEN-LAST:event_jComboBox_yearActionPerformed

    private void jComboBox_semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_semActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        // TODO add your handling code here:
        Student_Welcome_form object=new Student_Welcome_form();
        object.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
            //String sql="SELECT STUDENT_ID,COURSE_CODE,SEMESTER,TYPE,CREDIT FROM COURSE WHERE STUDENT_ID=? and SEMESTER =?";
           int gootidint=employee.empid;
           
            String gotiid=String.valueOf(gootidint);
           String got2=jComboBox_sem.getSelectedItem().toString();
           String got3=jComboBox_year.getSelectedItem().toString();
             String sql="select SEMESTER,COURSE_CODE,YEAR from course where STUDENT_ID ='"+gotiid+"'and SEMESTER='"+got2+"' and YEAR='"+got3+"'";
             //String sql3="SELECT SEMESTER,COURSE_CODE,TYPE FROM COURSE UNION SELECT GRADE,SEMESTER FROM table2";
            try {
                pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            
            rs=(OracleResultSet) pst.executeQuery();
             jTable_assigned_course.setModel(DbUtils.resultSetToTableModel(rs));
             jLabel_Semester.setText(got2);
             jLabel_year.setText(got3);
             
        
    } catch (Exception e) {
        
                JOptionPane.showMessageDialog(null, e);
    }
    
           
            /*if(rs.isClosed())
            {
          
                       jTable_course.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else
            {
                JOptionPane.showMessageDialog(null,"No Course Assigned ");
              
         DefaultTableModel tMOdel = (DefaultTableModel) jTable_course.getModel();
tMOdel.setRowCount(0);
          
            }
             */
            
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
        } 
        try {
            creditmethod();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assigned_Course_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assigned_Course_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assigned_Course_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assigned_Course_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assigned_Course_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Retake_Credit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JComboBox<String> jComboBox_sem;
    private javax.swing.JComboBox<String> jComboBox_year;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Semester;
    private javax.swing.JLabel jLabel_regular_credit;
    private javax.swing.JLabel jLabel_retake_credit;
    private javax.swing.JLabel jLabel_sid;
    public javax.swing.JLabel jLabel_st;
    private javax.swing.JLabel jLabel_total_credit;
    private javax.swing.JLabel jLabel_year;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_assigned_course;
    // End of variables declaration//GEN-END:variables
}
