
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Drimik
 */
public class audit extends javax.swing.JFrame {
    Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
  
    /**
     * Creates new form audit
     */
    public audit() {
        initComponents();
       conn = JavaConnectDb.connectrDb();
        update_Table();
    }
    
    private void update_Table()
    {
         try{
         conn = JavaConnectDb.connectrDb();
         String sql = "SELECT * FROM AUDIT_TABLE ";
        
         pst = (OraclePreparedStatement) conn.prepareStatement(sql);
         rs=(OracleResultSet) pst.executeQuery();
         
         tbl_1.setModel(DbUtils.resultSetToTableModel(rs));
 }
     catch(SQLException e){
         JOptionPane.showMessageDialog(null, e);
         
     }
     
       /** try {
            String sql= "SELECT * FROM AUDIT_TABLE";
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
             tbl_1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        jB_logout = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_1 = new javax.swing.JTable();
        jB_logout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 11, 268, -1));

        jB_logout.setText("HOME");
        jB_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(jB_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        tbl_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 727, 283));

        jB_logout1.setText("Logout");
        jB_logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logout1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        jLabel1.setText("Search By ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 30));

        setBounds(0, 0, 751, 406);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        try {
            
            String sql= "SELECT * FROM AUDIT_TABLE WHERE EMP_ID=? " ;
            pst=(OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText().toString());
            rs=(OracleResultSet) pst.executeQuery();
            tbl_1.setModel(DbUtils.resultSetToTableModel(rs));
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "use eid"
                    + "");
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
                                             
        
        
        /*
         
        DefaultTableModel table=(DefaultTableModel)tbl_1.getModel();
        String search=txt_search.getText().toString();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<>(table);
        tbl_1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    update_Table();
        */
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jB_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logoutActionPerformed
        // TODO add your handling code here:
        login_2  c= new login_2();
        c.setVisible(true);
        this.dispose();
        try {
            Date curreDate=GregorianCalendar.getInstance().getTime();
            DateFormat df= DateFormat.getDateInstance();
            String dateString=df.format(curreDate);
            Date d= new Date();
            SimpleDateFormat sdf= new SimpleDateFormat("HH:MM:SS");
            String timeString=sdf.format(d);
            String valueo=timeString;
            String values =dateString;
            int value=employee.empid;
            String reg="INSERT INTO AUDIT_TABLE(EMP_ID,DATE_USE,STATUS) VALUES ('"+value+ "','"+valueo+" / "+values+"','logged out' )";
            pst=(OraclePreparedStatement) conn.prepareStatement(reg);
            pst.executeQuery();
        } catch (Exception e) {
        }
        finally{try {
            rs.close();
            pst.close();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jB_logoutActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void jB_logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(audit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new audit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_logout;
    private javax.swing.JButton jB_logout1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tbl_1;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    private void getModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private DefaultTableModel DefaultTableModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
