
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Drimik
 */
public class Course_List extends javax.swing.JFrame {
  Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    /**
    /**
     * Creates new form Course_List
     */
    public Course_List() {
        initComponents();
        showTableData();
    }
        public void showTableData(){
     try{
         conn = JavaConnectDb.connectrDb();
         String sql = "SELECT * FROM COURSE_LIST ";
        
         pst = (OraclePreparedStatement) conn.prepareStatement(sql);
         rs=(OracleResultSet) pst.executeQuery();
         
         jtable_course_list.setModel(DbUtils.resultSetToTableModel(rs));
 }
     catch(SQLException e){
         JOptionPane.showMessageDialog(null, e);
         
     }
     


 }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_course_list = new javax.swing.JTable();
        jText_cname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jText_credit = new javax.swing.JTextField();
        jText_code = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtable_course_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course_name", "Course_Code", "Credit"
            }
        ));
        jtable_course_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable_course_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable_course_list);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 68, 590, 350));
        getContentPane().add(jText_cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 151, 255, 39));

        jLabel2.setText("Course_Code");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 208, 86, 33));

        jLabel3.setText("Course_Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 146, 86, 33));
        getContentPane().add(jText_credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 262, 255, 39));
        getContentPane().add(jText_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 208, 255, 39));

        jLabel4.setText("Credit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 265, 86, 33));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 110, 30));

        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 140, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtable_course_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable_course_listMouseClicked
           int i=jtable_course_list.getSelectedRow();
         String Table_click= (jtable_course_list.getModel().getValueAt(i,0).toString());
        TableModel model=jtable_course_list.getModel();
        jText_cname.setText(model.getValueAt(i,0).toString());
        jText_code.setText(model.getValueAt(i,1).toString());
        jText_credit.setText(model.getValueAt(i,2).toString());
        
        
             // TODO add your handling code here:
    }//GEN-LAST:event_jtable_course_listMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        student_main_form st1=new student_main_form();
        st1.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed

        try{
            String valueid=jText_code.getText();
            String sql = "UPDATE COURSE_LIST set COURSENAME=?,COURSECODE=?,CREDIT=? where COURSECODE='"+valueid+"'";

            conn =  JavaConnectDb.connectrDb();
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1,jText_cname.getText());
            pst.setString(2,valueid);
            pst.setString(3,jText_credit.getText());
            

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated  successfully");
             showTableData();
           

        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
          

        }      
    }//GEN-LAST:event_jButton_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course_List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText_cname;
    private javax.swing.JTextField jText_code;
    private javax.swing.JTextField jText_credit;
    private javax.swing.JTable jtable_course_list;
    // End of variables declaration//GEN-END:variables
}
