
import java.sql.Connection;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import java.util.Calendar;
import java.util.Date;
import  java.util.GregorianCalendar;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Drimik
 */
public class StatisticsMain extends javax.swing.JFrame {

     Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;

    public StatisticsMain() {
        initComponents();
        countmethodmale();
        countmethodfemale();
        countmethodtotalstudent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void countmethodmale() 
    {
        try {
             String sql="select count(gender) from personal_details where gender='Male'";
        conn=JavaConnectDb.connectrDb();
        pst=(OraclePreparedStatement) conn.prepareStatement(sql);
        rs=  (OracleResultSet) pst.executeQuery();
        while(rs.next())
        {
               jLabel_male.setText(rs.getString(1));
        }
    
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally {try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, e);
                }
}
       
    }
     public void countmethodfemale() 
    {
       
        try {
             String sql="select count(gender) from personal_details where gender='Female'";
        conn=JavaConnectDb.connectrDb();
        pst=(OraclePreparedStatement) conn.prepareStatement(sql);
        rs=  (OracleResultSet) pst.executeQuery();
        while(rs.next())
        {  jLabel_Female.setText(rs.getString(1));}
     
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally {try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, e);
                }
        
       
    }
    }
      public void countmethodtotalstudent() 
    {
        try {
             String sql="select count(ID) from personal_details";
        conn=JavaConnectDb.connectrDb();
        pst=(OraclePreparedStatement) conn.prepareStatement(sql);
        rs=  (OracleResultSet) pst.executeQuery();
        while(rs.next())
        { jLabel_totalStudent.setText(rs.getString(1));}
      
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally {try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, e);
                }
        
       
    }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Female = new javax.swing.JLabel();
        jLabel_male = new javax.swing.JLabel();
        jLabel_totalStudent = new javax.swing.JLabel();
        jButton_female = new javax.swing.JButton();
        jButton_male = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 60, 40));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 2, true), "J_Table_VIew_ Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 15), new java.awt.Color(51, 0, 255))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 50));

        jLabel_Female.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel_Female.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_Female.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 2, true), "Female Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 15), new java.awt.Color(51, 0, 255))); // NOI18N
        getContentPane().add(jLabel_Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 44));

        jLabel_male.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel_male.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_male.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 2, true), "Male Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 15), new java.awt.Color(51, 0, 255))); // NOI18N
        getContentPane().add(jLabel_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, 44));

        jLabel_totalStudent.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel_totalStudent.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_totalStudent.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 2, true), "Total Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 15), new java.awt.Color(51, 0, 255))); // NOI18N
        getContentPane().add(jLabel_totalStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, 44));

        jButton_female.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton_female.setForeground(new java.awt.Color(255, 0, 0));
        jButton_female.setText("Female");
        jButton_female.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_femaleActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 115, 34));

        jButton_male.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton_male.setForeground(new java.awt.Color(255, 0, 0));
        jButton_male.setText("male");
        jButton_male.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_maleActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 115, 34));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 30, 280, 200));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      student_main_form smff=new student_main_form();
      smff.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_maleActionPerformed
       NewJInternalFrame nji=new NewJInternalFrame();
 jDesktopPane1.add(nji);
 nji.show();
        
       male_view mv=new male_view();
       mv.setVisible(true);
       this.dispose();
 
 
    
      
    }//GEN-LAST:event_jButton_maleActionPerformed

    private void jButton_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_femaleActionPerformed
        // TODO add your handling code here:
        Female_View fmv=new Female_View();
        fmv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_femaleActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_female;
    private javax.swing.JButton jButton_male;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Female;
    private javax.swing.JLabel jLabel_male;
    private javax.swing.JLabel jLabel_totalStudent;
    // End of variables declaration//GEN-END:variables
}
