
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Drimik
 */
public class student_main_form extends javax.swing.JFrame {
Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    
    public student_main_form() {
      
        initComponents();
          conn = JavaConnectDb.connectrDb();
        jLabel_loggedid.setText(String.valueOf(employee.empid).toString());
        jLabel3_ok.setText(employee.Empstring);
        showcount();
    }
    
public void showcount()
        
{
    String sql="SELECT COUNT(TYPE) FROM LOGIN";
    try {
        pst=(OraclePreparedStatement) conn.prepareStatement(sql);
        rs=(OracleResultSet) pst.executeQuery();
        while(rs.next())
        {
            int ik=rs.getInt(1);
            String ik2=String.valueOf(ik);
          lbl_total.setText(ik2);
        }
        

    } catch (Exception e) {
    }
   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_loggedid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jB_logout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton_Course_search_course = new javax.swing.JButton();
        jButton_Course_assign = new javax.swing.JButton();
        jButton_Course_add_course = new javax.swing.JButton();
        jButton_add_result = new javax.swing.JButton();
        jButton_Course5 = new javax.swing.JButton();
        jButton_Course6 = new javax.swing.JButton();
        jButton_Course7 = new javax.swing.JButton();
        jButton_Course9 = new javax.swing.JButton();
        jLabel3_ok = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton_Course3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton_Course4 = new javax.swing.JButton();
        jButton_Course11 = new javax.swing.JButton();
        jButton_Course12 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        jMenu1.setText("jMenu1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Drimik\\Documents\\images (1).png")); // NOI18N
        jLabel7.setText("jLabel7");

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 255), 3, true));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("WELCOME");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204), 3));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 44));

        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3), "Course_Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 260, 40));

        jLabel_loggedid.setBackground(new java.awt.Color(255, 204, 0));
        jLabel_loggedid.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        jLabel_loggedid.setForeground(new java.awt.Color(204, 0, 204));
        jLabel_loggedid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));
        jPanel1.add(jLabel_loggedid, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 70, 40));

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("logged_ID");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204), 3));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 130, 40));

        jLabel6.setBackground(new java.awt.Color(153, 153, 255));
        jLabel6.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Total_USER");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204), 3));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 150, 44));

        lbl_total.setBackground(new java.awt.Color(255, 204, 0));
        lbl_total.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(204, 0, 204));
        lbl_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));
        jPanel1.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 70, 40));

        jB_logout.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jB_logout.setForeground(new java.awt.Color(255, 51, 51));
        jB_logout.setText("Logout");
        jB_logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jB_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(jB_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 120, 50));

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("AUDIT");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 90, 50));

        jButton2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 153), 4));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 50));

        jButton4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 51));
        jButton4.setText("Semester Registration");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 300, 50));

        jButton5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton5.setText("Add");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 153), 4));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 50));

        jButton6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton6.setText("Single_search");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 153), 4));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, 50));

        jButton_Course_search_course.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course_search_course.setText("search");
        jButton_Course_search_course.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 4, true));
        jButton_Course_search_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course_search_courseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course_search_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 130, 30));

        jButton_Course_assign.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course_assign.setText("Course_assign");
        jButton_Course_assign.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 4, true));
        jButton_Course_assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course_assignActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course_assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 110, 40));

        jButton_Course_add_course.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course_add_course.setText("Add");
        jButton_Course_add_course.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 4, true));
        jButton_Course_add_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course_add_courseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course_add_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 90, 30));

        jButton_add_result.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_add_result.setText("Add");
        jButton_add_result.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 4));
        jButton_add_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_resultActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_add_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 100, 50));

        jButton_Course5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course5.setText("search");
        jButton_Course5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 4));
        jButton_Course5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 100, 50));

        jButton_Course6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course6.setForeground(new java.awt.Color(51, 51, 255));
        jButton_Course6.setText("Update");
        jButton_Course6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153), 4));
        jButton_Course6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 90, 50));

        jButton_Course7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course7.setText("Statistics");
        jButton_Course7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 4));
        jButton_Course7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 180, 50));

        jButton_Course9.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course9.setForeground(new java.awt.Color(51, 51, 255));
        jButton_Course9.setText("Create");
        jButton_Course9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153), 4));
        jButton_Course9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 90, 50));

        jLabel3_ok.setBackground(new java.awt.Color(255, 204, 0));
        jLabel3_ok.setFont(new java.awt.Font("Agency FB", 3, 18)); // NOI18N
        jLabel3_ok.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3_ok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));
        jPanel1.add(jLabel3_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 180, 44));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3), "Result_Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 110));

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3), "Account_Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 250, 230));

        jButton7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton7.setText("jTable_Search ");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 153), 4));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, 50));

        jLabel8.setBackground(new java.awt.Color(255, 51, 204));
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3), "Student_Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 340, 270));

        jButton_Course3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course3.setText("Update");
        jButton_Course3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 4, true));
        jButton_Course3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 220, 30));

        jButton9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 51, 51));
        jButton9.setText("FEES");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 300, 50));

        jButton_Course4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course4.setText("Student View in semester");
        jButton_Course4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 4, true));
        jButton_Course4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 220, 40));

        jButton_Course11.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course11.setText("List");
        jButton_Course11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 4, true));
        jButton_Course11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 110, 40));

        jButton_Course12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_Course12.setText("ADD_Faculty");
        jButton_Course12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 4));
        jButton_Course12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Course12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Course12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 180, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Drimik\\Documents\\ICON\\background-1.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, -10, 220, 570));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Drimik\\Documents\\ICON\\background-1.jpg")); // NOI18N
        jLabel11.setText("jLabel10");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 940, 570));

        jMenu2.setText("File");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(989, 612));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
 audit objj= new audit();
 objj.show();// TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        audit ne=new audit();
        ne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logoutActionPerformed
        // TODO add your handling code here:
        login_2  c= new login_2();
        c.setVisible(true);
        this.dispose();
        try {
            Date curreDate=GregorianCalendar.getInstance().getTime();
            DateFormat df= DateFormat.getDateInstance();
            String dateString=df.format(curreDate);
            Date d= new Date();
            SimpleDateFormat sdf= new SimpleDateFormat("HH:MM:SS");
            String timeString=sdf.format(d);
            String valueo=timeString;
            String values =dateString;
            int value=employee.empid;
            String valuetype=employee.Emptype;
            String reg="INSERT INTO AUDIT_TABLE(TYPE,EMP_ID,DATE_USE,STATUS) VALUES ('"+valuetype+ "','"+value+ "','"+valueo+" / "+values+"','logged out' )";
            pst=(OraclePreparedStatement) conn.prepareStatement(reg);
            pst.executeQuery();
        } catch (Exception e) {
        }
        finally{try {
            rs.close();
            pst.close();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jB_logoutActionPerformed

    private void jButton_Course_search_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course_search_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Course_search_courseActionPerformed

    private void jButton_Course_assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course_assignActionPerformed
ADD_Courses ac=new ADD_Courses();
ac.setVisible(true);//
this.dispose();
//TODO add your handling code here:
    }//GEN-LAST:event_jButton_Course_assignActionPerformed

    private void jButton_Course_add_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course_add_courseActionPerformed
     Course_ADDing cs=new Course_ADDing();
     cs.setVisible(true);
     this.dispose();
        
    }//GEN-LAST:event_jButton_Course_add_courseActionPerformed

    private void jButton_add_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_resultActionPerformed
        ADD_RESULT ar= new ADD_RESULT();
        ar.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton_add_resultActionPerformed

    private void jButton_Course5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Course5ActionPerformed

    private void jButton_Course7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course7ActionPerformed
StatisticsMain sf=new StatisticsMain();
sf.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton_Course7ActionPerformed

    private void jButton_Course9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course9ActionPerformed
       ADD_ACCOUNT ac=new ADD_ACCOUNT();
       ac.setVisible(true);
       this.dispose();
       
       
    }//GEN-LAST:event_jButton_Course9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      ADD_Student as= new ADD_Student();
      as.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Student_1 o1=new Student_1();
o1.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton_Course3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course3ActionPerformed
Course_List cl=new Course_List();
cl.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton_Course3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
Semester_Registration sr= new Semester_Registration();
sr.setVisible(true);
this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
FEESS fe= new FEESS();
fe.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton_Course4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course4ActionPerformed
Course_List cl= new Course_List();
cl.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton_Course4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     Search_IN_JTABLE aij=new Search_IN_JTABLE();
           aij.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Update_student us=new Update_student();
us.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_Course11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course11ActionPerformed
 Course_List_View clv=new Course_List_View();
 clv.setVisible(true);
 this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton_Course11ActionPerformed

    private void jButton_Course12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course12ActionPerformed
ADD_FACULTY afc=new ADD_FACULTY();
afc.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton_Course12ActionPerformed

    private void jButton_Course6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Course6ActionPerformed

    }//GEN-LAST:event_jButton_Course6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_main_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_main_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_logout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_Course11;
    private javax.swing.JButton jButton_Course12;
    private javax.swing.JButton jButton_Course3;
    private javax.swing.JButton jButton_Course4;
    private javax.swing.JButton jButton_Course5;
    private javax.swing.JButton jButton_Course6;
    private javax.swing.JButton jButton_Course7;
    private javax.swing.JButton jButton_Course9;
    private javax.swing.JButton jButton_Course_add_course;
    private javax.swing.JButton jButton_Course_assign;
    private javax.swing.JButton jButton_Course_search_course;
    private javax.swing.JButton jButton_add_result;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel3_ok;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabel_loggedid;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbl_total;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    // End of variables declaration//GEN-END:variables
}
