
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.RadioButton;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Drimik
 */
public class Update_student extends javax.swing.JFrame {
 Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    
    public Update_student() {
        initComponents();
        conn=JavaConnectDb.connectrDb();
        showTableData();
    }
      public ImageIcon ResizeImage(String ImagePath)
    {
      ImageIcon MyImage= new ImageIcon(ImagePath);
      Image img = MyImage.getImage();
      Image newImg= img.getScaledInstance(image.getWidth(),image.getHeight(),Image.SCALE_SMOOTH);
      ImageIcon image= new ImageIcon(newImg);
      return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void showTableData(){
     try{
      
         String sql = "SELECT * FROM PERSONAL_DETAILS ";
        
         pst = (OraclePreparedStatement) conn.prepareStatement(sql);
      
         rs=(OracleResultSet) pst.executeQuery();
         
     jTable_student.setModel(DbUtils.resultSetToTableModel(rs));
 
     }
     catch(SQLException e){
         JOptionPane.showMessageDialog(null, e);
         
     }
     
     finally{
         try {
             pst.close();
             rs.close();
         } catch (Exception e) {
         }
     }


 }
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mygroup = new javax.swing.ButtonGroup();
        Try = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        first_nam_text = new javax.swing.JTextField();
        fathers_name_text = new javax.swing.JTextField();
        mothers_name_text = new javax.swing.JTextField();
        last_name_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DOB_text = new javax.swing.JTextField();
        religion_txt = new javax.swing.JTextField();
        dpt_text = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Intake_text = new javax.swing.JTextField();
        Section_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton_chooser = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        jButton_update = new javax.swing.JButton();
        limon_text = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_student = new javax.swing.JTable();
        religion_txt1 = new javax.swing.JTextField();
        gender_txt = new javax.swing.JTextField();
        age_text_final = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jB_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("S_ID");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("First_Name");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Last_Name");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 97, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Father's Name");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Mother's Name");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("Address");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 60, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("Religion");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 358, 110, 30));

        id_text.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textActionPerformed(evt);
            }
        });
        id_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_textKeyReleased(evt);
            }
        });
        getContentPane().add(id_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 180, 30));

        first_nam_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        first_nam_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nam_textActionPerformed(evt);
            }
        });
        getContentPane().add(first_nam_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 180, 30));

        fathers_name_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fathers_name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathers_name_textActionPerformed(evt);
            }
        });
        getContentPane().add(fathers_name_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 180, 30));

        mothers_name_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mothers_name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mothers_name_textActionPerformed(evt);
            }
        });
        getContentPane().add(mothers_name_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, 30));

        last_name_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        last_name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_name_txtActionPerformed(evt);
            }
        });
        getContentPane().add(last_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, 30));

        address_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });
        getContentPane().add(address_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 170, 102));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setText("Age");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setText("gender");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 90, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setText("DOB");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 100, 30));

        DOB_text.setText("DD-MM-YY");
        DOB_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DOB_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOB_textActionPerformed(evt);
            }
        });
        getContentPane().add(DOB_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 180, 30));

        religion_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        religion_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religion_txtActionPerformed(evt);
            }
        });
        getContentPane().add(religion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 180, 30));

        dpt_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dpt_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpt_textActionPerformed(evt);
            }
        });
        getContentPane().add(dpt_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 170, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Department");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 30));

        Intake_text.setText("Numeric Form");
        Intake_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Intake_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Intake_textMouseClicked(evt);
            }
        });
        Intake_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Intake_textActionPerformed(evt);
            }
        });
        getContentPane().add(Intake_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 170, 30));

        Section_text.setText("Numeric Form");
        Section_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Section_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Section_textActionPerformed(evt);
            }
        });
        getContentPane().add(Section_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel10.setText("Intake");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("Section");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 30));

        jButton_chooser.setBackground(new java.awt.Color(255, 51, 51));
        jButton_chooser.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_chooser.setForeground(new java.awt.Color(51, 0, 255));
        jButton_chooser.setText("Choose");
        jButton_chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_chooserActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 210, 30));

        image.setBackground(new java.awt.Color(0, 0, 0));
        image.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        image.setForeground(new java.awt.Color(255, 153, 153));
        image.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(51, 255, 0), new java.awt.Color(0, 102, 51)));
        image.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 200, 150));

        jButton_update.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_update.setForeground(new java.awt.Color(51, 0, 255));
        jButton_update.setText("Update");
        jButton_update.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 90, 50));

        limon_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        limon_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limon_textActionPerformed(evt);
            }
        });
        getContentPane().add(limon_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 200, 30));

        jButton3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButton3.setText("Display");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 100, 30));

        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 4), "Button", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 620, 100));

        jButton4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("BACK");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 90, 50));

        jButton5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("HOME");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, 90, 50));

        jButton_delete.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton_delete.setForeground(new java.awt.Color(0, 0, 255));
        jButton_delete.setText("Delete");
        jButton_delete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 90, 50));

        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4), "Academic_Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 170, 790));

        jTable_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_studentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable_studentMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_student);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 660, 200));

        religion_txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        religion_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religion_txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(religion_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 180, 30));
        getContentPane().add(gender_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 170, 30));

        age_text_final.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        age_text_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_text_finalActionPerformed(evt);
            }
        });
        getContentPane().add(age_text_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 180, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 250, 200));

        jB_logout.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jB_logout.setForeground(new java.awt.Color(255, 51, 51));
        jB_logout.setText("Logout");
        jB_logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jB_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(jB_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 120, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textActionPerformed

    private void first_nam_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nam_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_nam_textActionPerformed

    private void fathers_name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathers_name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathers_name_textActionPerformed

    private void mothers_name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mothers_name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mothers_name_textActionPerformed

    private void last_name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_name_txtActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void DOB_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOB_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOB_textActionPerformed

    private void religion_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religion_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religion_txtActionPerformed

    private void dpt_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpt_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpt_textActionPerformed

    private void Intake_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Intake_textMouseClicked
        Intake_text.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Intake_textMouseClicked

    private void Intake_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Intake_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Intake_textActionPerformed

    private void Section_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Section_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Section_textActionPerformed

    private void jButton_chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_chooserActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        File f=  chooser.getSelectedFile();
        int Result = 0;
        if(Result==JFileChooser.APPROVE_OPTION)
        {

            Filename= f.getAbsolutePath();
            limon_text.setText(Filename);
            image.setIcon(ResizeImage(Filename));
        }

        try{

            File image=new File (Filename);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf= new byte[1024];
            for(int readNum ;(readNum = fis.read(buf))!=-1;)

            {
                bos.write(buf,0,readNum);
            }
            person_image= bos.toByteArray();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton_chooserActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:

        try{
            String valueid=id_text.getText();
            String sql = "UPDATE personal_details set ID=?,first_name=?,last_name=?,fathers_name=?,mothers_name=?,address=?,religion=?,department=?,intake=?,section=?,age=?,gender=?,dob=?,pic=? where ID='"+valueid+"'";

            conn =  JavaConnectDb.connectrDb();
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1,id_text.getText());
            pst.setString(2,first_nam_text.getText());
            pst.setString(3,last_name_txt.getText());
            pst.setString(4,fathers_name_text.getText());
            pst.setString(5, mothers_name_text.getText());
            pst.setString(6, address_txt.getText());
            pst.setString(7, religion_txt.getText());
            pst.setString(8,dpt_text.getText());
            pst.setString(9,Intake_text.getText());

            pst.setString(10,Section_text.getText());
            pst.setString(11,age_text_final.getText());
            pst.setString(12,gender_txt.getText());
            

            pst.setString(13,DOB_text.getText());

            pst.setBytes(14, person_image);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated  successfully");
             showTableData();
           

        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null,"check the constraint ID must be DIGIT  ");

        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void limon_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limon_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limon_textActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        image.setIcon(null);        // TODO add your handling code here:
        try {
            String sql = "select PIC from personal_details where ID=?";
            conn =  JavaConnectDb.connectrDb();
            pst = (OraclePreparedStatement) conn.prepareStatement(sql);
            pst.setString(1,id_text.getText());
            rs=(OracleResultSet) pst.executeQuery();

            if(rs.next())
            {

                byte [] imagedata = rs.getBytes("pic") ;
                BufferedImage buff_image=ImageIO.read(new ByteArrayInputStream(imagedata));
                format = new ImageIcon(buff_image);
                image.setIcon(format);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        try{
        }
        catch(Exception e)
        {
        }
        finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        student_main_form sdd=new student_main_form();
      sdd.setVisible(true);
      this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        
        try {
             String valueid=id_text.getText();
        String sql="DELETE FROM PERSONAL_DETAILS WHERE ID ='"+valueid+"'";
         conn =  JavaConnectDb.connectrDb();
        pst= (OraclePreparedStatement) conn.prepareStatement(sql);
        pst.executeQuery();
        JOptionPane.showMessageDialog(null,"delete Succefully");
        showTableData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e);
        }
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jTable_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_studentMouseClicked
       int i=jTable_student.getSelectedRow();
         String Table_click= (jTable_student.getModel().getValueAt(i,0).toString());
        TableModel model=jTable_student.getModel();
        
 id_text.setText(model.getValueAt(i,0).toString());
 first_nam_text.setText(model.getValueAt(i,1).toString());    
 last_name_txt.setText(model.getValueAt(i,2).toString());
 fathers_name_text.setText(model.getValueAt(i,3).toString());
mothers_name_text.setText(model.getValueAt(i,4).toString());
address_txt.setText(model.getValueAt(i,5).toString());
religion_txt.setText(model.getValueAt(i,6).toString());
dpt_text.setText(model.getValueAt(i,7).toString());
Intake_text.setText(model.getValueAt(i,8).toString());
Section_text.setText(model.getValueAt(i,9).toString());
age_text_final.setText(model.getValueAt(i,10).toString());

//gender
DOB_text.setText(model.getValueAt(i,12).toString());
//picture

  
        if(jTable_student.getValueAt(i, 13) != null)
        {
        ImageIcon image1 = (ImageIcon)jTable_student.getValueAt(i, 13);
        Image image2 = image1.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image3 = new ImageIcon(image2);
        jLabel1.setIcon(image3);
        
        }
        else{
            System.out.println("No Image");
        }
    
// TODO add your handling code here:
    }//GEN-LAST:event_jTable_studentMouseClicked

    private void id_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_textKeyReleased
String sql="select * from PERSONAL_DETAILS where ID=?";
        try {
        
     

      

            pst= (OraclePreparedStatement) conn.prepareStatement(sql);
            String str=id_text.getText();
            pst.setString(1, str);

 

            //Excuting Query

                   rs = (OracleResultSet) pst.executeQuery();
            if(rs.next())
            {
                
                String s1 = rs.getString("ID");
                String s2 = rs.getString("FIRST_NAME");
                String s3 = rs.getString("LAST_NAME");
                String s4 = rs.getString("FATHERS_NAME");
                String s5 = rs.getString("MOTHERS_NAME");
                String s6 = rs.getString("ADDRESS");
                String s7 = rs.getString("RELIGION");
                String s8=  rs.getString("DEPARTMENT");
                String s9=  rs.getString("INTAKE");
                String s10=  rs.getString("SECTION");
                String s11=  rs.getString("AGE");
                String s12=  rs.getString("GENDER");
                
                String s13=  rs.getString("DOB");
               
                            

 
                

                //Sets Records in TextFields.

            
                  
                  id_text.setText(s1);
                 first_nam_text.setText(s2);
                  last_name_txt.setText(s3);
                  fathers_name_text.setText(s4);
                  mothers_name_text.setText(s5);
                 address_txt.setText(s6);
                  religion_txt.setText(s7);
                  dpt_text.setText(s8);
                  Intake_text.setText(s9);
                  Section_text.setText(s10);
                 age_text_final.setText(s11);
                gender_txt.setText(s12);
                
                  DOB_text.setText(s13);
                  
                    
              
                  
                   
                
                
                
                
                

                

            } else {

                JOptionPane.showMessageDialog(null, "Name not Found");

            }
             image.setIcon(null);        // TODO add your handling code here:
                 try {
            String sql2 = "select PIC from personal_details where ID=?";
              conn =  JavaConnectDb.connectrDb();
              pst = (OraclePreparedStatement) conn.prepareStatement(sql);
              pst.setString(1,id_text.getText());
              rs=(OracleResultSet) pst.executeQuery();
              
                
              if(rs.next())
              {
                
             byte [] imagedata = rs.getBytes("pic") ;
             BufferedImage buff_image=ImageIO.read(new ByteArrayInputStream(imagedata));
               format = new ImageIcon(buff_image);
             image.setIcon(format);
             
             
              }
        } catch (Exception e) {
            e.printStackTrace();
        }
                
        
        
    }
        
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"got some problem");
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_id_textKeyReleased

    private void religion_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religion_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religion_txt1ActionPerformed

    private void jTable_studentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_studentMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_studentMouseEntered

    private void age_text_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_text_finalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_text_finalActionPerformed

    private void jB_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_logoutActionPerformed
        // TODO add your handling code here:
        login_2  c= new login_2();
        c.setVisible(true);
        this.dispose();
        try {
            Date curreDate=GregorianCalendar.getInstance().getTime();
            DateFormat df= DateFormat.getDateInstance();
            String dateString=df.format(curreDate);
            Date d= new Date();
            SimpleDateFormat sdf= new SimpleDateFormat("HH:MM:SS");
            String timeString=sdf.format(d);
            String valueo=timeString;
            String values =dateString;
            int value=employee.empid;
            String reg="INSERT INTO AUDIT_TABLE(EMP_ID,DATE_USE,STATUS) VALUES ('"+value+ "','"+valueo+" / "+values+"','logged out' )";
            pst=(OraclePreparedStatement) conn.prepareStatement(reg);
            pst.executeQuery();
        } catch (Exception e) {
        }
        finally{try {
            rs.close();
            pst.close();
        } catch (Exception e) {
        }
        }
    }//GEN-LAST:event_jB_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOB_text;
    private javax.swing.JTextField Intake_text;
    private javax.swing.ButtonGroup Mygroup;
    private javax.swing.JTextField Section_text;
    private javax.swing.ButtonGroup Try;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField age_text_final;
    private javax.swing.JTextField dpt_text;
    private javax.swing.JTextField fathers_name_text;
    private javax.swing.JTextField first_nam_text;
    private javax.swing.JTextField gender_txt;
    private javax.swing.JTextField id_text;
    private javax.swing.JLabel image;
    private javax.swing.JButton jB_logout;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_chooser;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_student;
    private javax.swing.JTextField last_name_txt;
    private javax.swing.JTextField limon_text;
    private javax.swing.JTextField mothers_name_text;
    private javax.swing.JTextField religion_txt;
    private javax.swing.JTextField religion_txt1;
    // End of variables declaration//GEN-END:variables
String Filename=null;
int s=0;
byte[] person_image=null;
private  ImageIcon format=null;
}
